# Generated by Django 4.1.7 on 2023-03-11 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('anons', models.CharField(max_length=250)),
                ('full_text', models.TextField()),
                ('date', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
    ]
